ARG NODE_VERSION=22.20.0
ARG PNPM_VERSION=10.20.0

FROM node:${NODE_VERSION}-slim AS base

ARG PNPM_VERSION

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable && corepack prepare pnpm@${PNPM_VERSION} --activate

WORKDIR /app

FROM base AS dependencies

RUN apt-get update && apt-get install -y --no-install-recommends \
    openssl \
    ca-certificates \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY pnpm-workspace.yaml pnpm-lock.yaml package.json prisma.config.ts .npmrc ./
COPY apps/web/package.json ./apps/web/
COPY apps/background-jobs/package.json ./apps/background-jobs/
COPY packages/shared/package.json ./packages/shared/
COPY packages/prisma ./packages/prisma/

RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    pnpm install --frozen-lockfile

FROM dependencies AS builder

COPY apps ./apps
COPY packages ./packages
COPY tsconfig.json ./
COPY .npmrc ./
COPY prisma.config.ts ./

RUN pnpm --filter prisma generate

RUN pnpm rebuild @tailwindcss/oxide rollup sharp

RUN pnpm --filter shared build

RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    pnpm install --frozen-lockfile

RUN pnpm --filter web build

FROM base AS production

RUN apt-get update && apt-get install -y --no-install-recommends \
    openssl \
    ca-certificates \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/pnpm-workspace.yaml ./
COPY --from=builder /app/pnpm-lock.yaml ./
COPY --from=builder /app/package.json ./
COPY --from=builder /app/prisma.config.ts ./
COPY --from=builder /app/.npmrc ./

COPY --from=builder /app/apps/web/package.json ./apps/web/
COPY --from=builder /app/apps/background-jobs/package.json ./apps/background-jobs/
COPY --from=builder /app/packages/shared/package.json ./packages/shared/
COPY --from=builder /app/packages/prisma/package.json ./packages/prisma/
COPY --from=builder /app/packages/prisma/schema.prisma ./packages/prisma

RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    pnpm install --frozen-lockfile --prod=false

COPY --from=builder /app/packages/prisma ./packages/prisma
COPY --from=builder /app/packages/shared ./packages/shared
COPY --from=builder /app/apps/web ./apps/web

WORKDIR /app

ENV NODE_ENV=production
EXPOSE 3745

CMD ["sh", "-c", "\
  pnpm --filter prisma migrate deploy && \
  pnpm --filter prisma seed && \
  pnpm --filter web start --host 0.0.0.0 --port 3745 \
"]



FROM base AS development

RUN apt-get update && apt-get install -y --no-install-recommends \
    openssl \
    ca-certificates \
    curl \
    && rm -rf /var/lib/apt/lists/

WORKDIR /app

COPY pnpm-workspace.yaml pnpm-lock.yaml package.json prisma.config.ts ./
COPY apps ./apps
COPY packages ./packages
COPY tsconfig.json ./
COPY .npmrc ./
COPY prisma.config.ts ./

RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    pnpm install --frozen-lockfile

WORKDIR /app

ENV NODE_ENV=development

EXPOSE 3745

CMD ["sh", "-c", "\
  pnpm --filter prisma migrate:deploy && \
  pnpm --filter prisma seed && \
  pnpm --filter web dev --host 0.0.0.0 --port 3745  \
"]
